import './globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { Suspense } from 'react';
import Loading from './components/loading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
            {children}
        </Suspense>
      </body>
    </html>
  );
}
